g.addEdge(Edge(g.getNode('ABC'), g.getNode('ABC')))
g.addEdge(Edge(g.getNode('BCA'), g.getNode('BAC')))
g.addEdge(Edge(g.getNode('CAB'), g.getNode('CBA')))
g.addEdge(Edge(g.getNode('BAC'), g.getNode('ABC')))
g.addEdge(Edge(g.getNode('BCA'), g.getNode('CBA')))
g.addEdge(Edge(g.getNode('ACB'), g.getNode('CAB')))